service: dsconstruction-photos

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  serverless-offline:
    port: 3003
  webpack:
    includeModules: true
    packager: "yarn"
    individually: true
  s3:
    bucketName: dsc-photos-${self:provider.stage}

provider:
  name: aws
  runtime: nodejs8.10
  region: ca-central-1
  stage: ${opt:stage, "dev"}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:PutObject
      Resource: arn:aws:s3:::${self:custom.s3.bucketName}
  environment:
    DSC_BUCKET_NAME: ${self:custom.s3.bucketName}

functions:
  getSignedUrl:
    handler: src/index.handler
    events:
      - http:
          path: /api/upload
          method: POST
          cors: true

resources:
  Resources:
    S3BucketPhotos:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.s3.bucketName}
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - "*"
              AllowedHeaders:
                - "*"
              AllowedMethods:
                - "GET"
                - "PUT"
                - "DELETE"
