service: dsconstruction-users

plugins:
  - serverless-webpack
  # - serverless-dynamodb-local
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  serverless-offline:
    port: 3002
  webpack:
    includeModules: true
    packager: "yarn"
    individually: true
  cognito:
    userPool:
      name: dsc-user-pool-${self:provider.stage}
    client:
      name: dsc-fuser-pool-client-${self:provider.stage}
  # dynamodb:
  #   stages:
  #     - dev
  #   start:
  #     port: 8000
  #     inMemory: true
  #     heapInitial: 200m
  #     heapMax: 1g
  #     migrate: true
  #     seed: true
  #     convertEmptyValues: true

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  stage: ${opt:stage, "dev"}
  environment:
    COGNITO_USER_POOL_ID:
      Ref: CognitoUserPool
    COGNITO_USER_POOL_CLIENT_ID:
      Ref: CognitoUserPoolClient
    COGNITO_USER_POOL_REGION: ${self:provider.region}

functions:
  login:
    handler: src/index.handler
    events:
      - http:
          path: /api/login
          method: POST
          cors: true
  resetTemporaryPassword:
    handler: src/index.handler
    events:
      - http:
          path: /api/reset/temporary
          method: POST
          cors: true
  create:
    handler: src/index.handler
    events:
      - http:
          path: /api/create
          method: POST
          cors: true

resources:
  Resources:
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:custom.cognito.userPool.name}
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
        Schema:
          - Name: email
            AttributeDataType: String
            Mutable: true
            Required: true
          - Name: name
            AttributeDataType: String
            Mutable: true
            Required: true
          - Name: family_name
            AttributeDataType: String
            Mutable: true
            Required: true
    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:custom.cognito.client.name}
        UserPoolId:
          Ref: CognitoUserPool
        ExplicitAuthFlows:
          - ADMIN_NO_SRP_AUTH
        GenerateSecret: false
  Outputs:
    UserPoolId:
      Value:
        Ref: CognitoUserPool
    UserPoolClientId:
      Value:
        Ref: CognitoUserPoolClient
