service: dsconstruction-backend

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  serverless-offline:
    port: 3001
  webpack:
    includeModules: true
    packager: "yarn"
    individually: true

provider:
  name: aws
  runtime: nodejs8.10
  region: ${opt:region, "ca-central-1"}
  stage: ${opt:stage, "dev"}
  environment:
    SERVERLESS_STAGE: ${self:provider.stage}

functions:
  home:
    handler: src/index.handler
    events:
      - http:
          path: /api/home
          method: GET
          cors: true
  getServices:
    handler: src/index.handler
    events:
      - http:
          path: /api/services
          method: GET
          cors: true
  destroyServices:
    handler: src/index.handler
    events:
      - http:
          path: /api/services
          method: DELETE
          cors: true
  addService:
    handler: src/index.handler
    events:
      - http:
          path: /api/services/add
          method: POST
          cors: true
  getGalleryPhotos:
    handler: src/index.handler
    events:
      - http:
          path: /api/gallery
          method: GET
          cors: true
  destroyGalleryPhotos:
    handler: src/index.handler
    events:
      - http:
          path: /api/gallery
          method: DELETE
          cors: true
  addGalleryPhoto:
    handler: src/index.handler
    events:
      - http:
          path: /api/gallery/add
          method: POST
          cors: true
