service: tom-fischer-backend

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    port: 3001
  webpack:
    includeModules: true
    packager: "yarn"
    individually: true

provider:
  name: aws
  runtime: nodejs8.10
  region: ${opt:region, "ca-central-1"}
  stage: ${opt:stage, "prod"}

functions:
  home:
    handler: src/index.handler
    events:
      - http:
          path: /api/home
          method: GET
          cors: true
  services:
    handler: src/index.handler
    events:
      - http:
          path: /api/services
          method: GET
          cors: true
